import { create } from "zustand";

export type LanguageCode = "es" | "en" | "de" | "fr" | "pt";
export type DateFormat = "DD/MM/YYYY" | "MM/DD/YYYY" | "YYYY-MM-DD";
export type NumberFormat = "en" | "de"; // en: 1,234.56, de: 1.234,56

export interface RegionalSettings {
    language: LanguageCode;
    dateFormat: DateFormat;
    numberFormat: NumberFormat;
    firstDayOfWeek: "monday" | "sunday";
}

const STORAGE_KEY = "nomadix_regional_preferences";
const LANG_STORAGE_KEY = "nomadix_language";

const DEFAULT_SETTINGS: RegionalSettings = {
    language: "es", // Default to Spanish as requested
    dateFormat: "DD/MM/YYYY",
    numberFormat: "en",
    firstDayOfWeek: "monday",
};

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
    es: {
        // Navigation
        "nav.dashboard": "Panel",
        "nav.vaults": "Bóvedas",
        "nav.expenses": "Gastos",
        "nav.subscriptions": "Suscripciones",
        "nav.reports": "Reportes",
        "nav.friends": "Amigos",
        "nav.identity": "Identidad",
        "nav.travel": "Viajes",
        "nav.settings": "Configuración",
        "nav.signOut": "Cerrar sesión",
        "nav.backToApp": "Volver a la app",

        // Settings Navigation
        "settings.account": "Cuenta",
        "settings.profile": "Perfil",
        "settings.privacy": "Privacidad y Amigos",
        "settings.preferences": "Preferencias",
        "settings.categories": "Categorías",
        "settings.ai": "Asistente IA",
        "settings.data": "Datos",
        "settings.security": "Seguridad",
        "settings.notifications": "Notificaciones",
        "settings.billing": "Facturación",
        "settings.language": "Idioma y Región",
        "settings.support": "Soporte",

        // Dashboard
        "dashboard.title": "Panel",
        "dashboard.welcome": "Hola de nuevo, {name}.",
        "dashboard.totalBalance": "Balance Total Combinado",
        "dashboard.active": "Activo",
        "dashboard.incomeVsExpenses": "Ingresos vs Gastos",
        "dashboard.last4Weeks": "Resumen de las últimas 4 semanas",
        "dashboard.week": "Semana",
        "dashboard.income": "Ingresos",
        "dashboard.expenses": "Gastos",
        "dashboard.checking": "Corriente",
        "dashboard.savings": "Ahorros",
        "dashboard.cash": "Efectivo",
        "dashboard.transactions": "Transacciones",
        "dashboard.noTransactions": "No hay transacciones todavía. ¡Agrega una!",
        "dashboard.viewAllTransactions": "Ver Todas las Transacciones",

        // Vaults
        "vaults.title": "Bóvedas",
        "vaults.subtitle": "Gestiona tus bóvedas financieras multimoneda.",
        "vaults.transaction": "Transacción",
        "vaults.newVault": "Nueva Bóveda",
        "vaults.totalAcrossAll": "Total en Todas las Bóvedas",
        "vaults.recentActivity": "Actividad Reciente",
        "vaults.filterAll": "Todo",
        "vaults.filterIncome": "Ingresos",
        "vaults.filterExpense": "Gastos",
        "vaults.filterTransfer": "Transferencias",
        "vaults.filterByCategory": "Filtrar por categoría",
        "vaults.categories": "Categorías",
        "vaults.categoriesCount": "Categorías ({count})",
        "vaults.search": "Buscar…",
        "vaults.clearFilter": "Limpiar filtro",
        "vaults.noResults": "Sin resultados.",
        "vaults.colDate": "Fecha",
        "vaults.colDescription": "Descripción",
        "vaults.colVault": "Bóveda",
        "vaults.colCategory": "Categoría",
        "vaults.colAmount": "Monto",
        "vaults.noTransactionsFound": "No se encontraron transacciones.",
        "vaults.loading": "Cargando...",
        "vaults.loadMore": "Ver más movimientos",
        "vaults.noMore": "No hay más movimientos.",
        "vaults.balance": "Balance",
        "vaults.pendingCollection": "Pendiente por Cobrar",
        "vaults.projectedTotal": "Total Proyectado",
        "vaults.receivableAccountsCount": "{count} cuentas",
        "vaults.receivableAccountsOverdue": "{count} cuentas · {overdue} vencida(s)",
        "vaults.type.savings": "Ahorros",
        "vaults.type.checking": "Corriente",
        "vaults.type.cash": "Efectivo",
        "vaults.type.receivable": "Pendiente por Cobrar",
        "vaults.myVaults": "Tus Bóvedas",
        "vaults.viewOptions": "Opciones de vista",
        "vaults.visibleLimitTitle": "Bóvedas visibles",
        "vaults.visibleLimitDesc": "Cantidad mostrada por defecto",
        "vaults.optionOneRow": "1 fila (4 bóvedas)",
        "vaults.optionTwoRows": "2 filas (8 bóvedas)",
        "vaults.optionThreeRows": "3 filas (12 bóvedas)",
        "vaults.optionAll": "Mostrar todas",
        "vaults.defaultBadge": "Predeterminado",
        "vaults.showMore": "Ver {count} más",
        "vaults.showLess": "Ver menos",

        // Expenses
        "expenses.title": "Gastos",
        "expenses.subtitle": "Analiza tus gastos por categoría y a lo largo del tiempo.",
        "expenses.converting": "Convirtiendo…",
        "expenses.dateRange": "Rango de fechas",
        "expenses.from": "Desde",
        "expenses.to": "Hasta",
        "expenses.vault": "Bóveda",
        "expenses.vaultFilter": "Filtro de bóveda",
        "expenses.allVaults": "Todas las bóvedas",
        "expenses.totalSpent": "Total gastado",
        "expenses.topCategory": "Categoría principal: {category} ({pct}%)",
        "expenses.periodVsPeriod": "Período vs período",
        "expenses.comparedToPrevious": "Comparado con los {days} días anteriores",
        "expenses.setDateRange": "Elegí un rango de fechas para comparar",
        "expenses.spendingOverTime": "Gasto a lo largo del tiempo",
        "expenses.categoryShare": "Distribución por categoría",
        "expenses.topCategoriesBySpend": "Categorías principales por gasto",
        "expenses.spendByCategory": "Gasto por categoría",
        "expenses.totalDistribution": "Total y distribución para los filtros seleccionados",
        "expenses.colCategory": "Categoría",
        "expenses.colTotal": "Total",
        "expenses.noExpensesFound": "No se encontraron gastos para los filtros seleccionados.",
        "expenses.highlights": "Destacados",
        "expenses.monthlyAverage": "Promedio mensual",
        "expenses.largestExpense": "Gasto más grande",
        "expenses.unknown": "Desconocido",
        "expenses.totalTransactions": "Total de transacciones",
        "expenses.filteredExpenses": "Gastos filtrados en el rango seleccionado",

        // Subscriptions
        "subs.title": "Suscripciones",
        "subs.subtitle": "Pagos e ingresos recurrentes",
        "subs.new": "Nueva Suscripción",
        "subs.filterAll": "Todas",
        "subs.filterActive": "Activas",
        "subs.filterPaused": "Pausadas",
        "subs.filterCanceled": "Canceladas",
        "subs.allVaults": "Todas las bóvedas",
        "subs.colSubscription": "Suscripción",
        "subs.colCycle": "Ciclo",
        "subs.colVault": "Bóveda",
        "subs.colNextCharge": "Próximo cargo",
        "subs.colAmount": "Monto",
        "subs.emptyTitle": "Todavía no hay suscripciones",
        "subs.emptySubtitle": "Registrá Netflix, alquiler, gimnasio, o cualquier ingreso recurrente.",
        "subs.mustBeLoggedIn": "Tenés que iniciar sesión para ver las suscripciones.",
        "subs.tablesNotSetUp": "Las tablas de suscripciones todavía no están configuradas. Corré supabase/schema.sql en el editor SQL de Supabase, después recargá el schema de la API (Settings → API → Reload schema).",
        "subs.stats.monthlyCost": "Costo mensual",
        "subs.stats.normalized": "Normalizado en todos los ciclos",
        "subs.stats.annualized": "Anualizado",
        "subs.stats.activeOne": "{count} suscripción activa",
        "subs.stats.activeMany": "{count} suscripciones activas",
        "subs.stats.next30Days": "Próximos 30 días",
        "subs.stats.chargeOne": "{count} cargo",
        "subs.stats.chargeMany": "{count} cargos",
        "subs.stats.recurringIncome": "Ingreso recurrente",
        "subs.stats.perMonth": "/mes",
        "subs.stats.incomeSub": "Salario, alquiler, freelance y más",
        "subs.detail.summaryAmount": "Monto",
        "subs.detail.summaryVault": "Bóveda",
        "subs.detail.summaryCategory": "Categoría",
        "subs.detail.summaryNextCharge": "Próximo cargo",
        "subs.detail.summaryMonthlyEq": "Equiv. mensual",
        "subs.detail.summaryAnnualized": "Anualizado",
        "subs.detail.subtotal": "Subtotal",
        "subs.detail.fee": "Fee",
        "subs.detail.total": "Total",
        "subs.detail.chargeNow": "Cobrar ahora",
        "subs.detail.skip": "Saltear este ciclo",
        "subs.detail.pause": "Pausar",
        "subs.detail.resume": "Reanudar",
        "subs.detail.cancel": "Cancelar suscripción",
        "subs.detail.confirmCancel": "¿Confirmar cancelación?",
        "subs.detail.edit": "Editar",
        "subs.detail.openCancelUrl": "Abrir página de cancelación",
        "subs.detail.paymentHistory": "Historial de pagos",
        "subs.detail.noCharges": "Todavía no hay cargos.",
        "subs.detail.inclFee": "incl. {amount} fee",
        "subs.confirm.title": "Confirmar cargo",
        "subs.confirm.dueLabel": "{name} · Vence {date}",
        "subs.confirm.amount": "Monto",
        "subs.confirm.vaultPrefix": "Bóveda:",
        "subs.confirm.note": "Nota (opcional)",
        "subs.confirm.willDeductFrom": "Esto va a descontar {amount} de {vault}.",
        "subs.confirm.willAddTo": "Esto va a agregar {amount} a {vault}.",
        "subs.confirm.theVault": "la bóveda",
        "subs.confirm.skip": "Saltear este ciclo",
        "subs.confirm.processing": "Procesando...",
        "subs.confirm.confirmCharge": "Confirmar cargo",
        "subs.confirm.invalidAmount": "Ingresá un monto válido.",
        "subs.widget.title": "Próximos cargos",
        "subs.widget.next30days": "Próximos 30 días",
        "subs.widget.viewAll": "Ver todo",
        "subs.widget.confirm": "Confirmar",
        "subs.widget.shortfall": "El balance puede caer por debajo de {zero} el {date}",
        "subs.widget.empty": "No hay cargos próximos en los próximos 30 días.",
        "subs.widget.addSubscription": "Agregar una suscripción →",
        "subs.toast.charged": "{name} cobrado",
        "subs.toast.skippedNamed": "{name}: se saltó este ciclo",
        "subs.toast.skipped": "Este ciclo se saltó",
        "subs.toast.paused": "Suscripción pausada",
        "subs.toast.resumed": "Suscripción reanudada",
        "subs.toast.canceled": "Suscripción cancelada",
        "subs.toast.updated": "Suscripción actualizada",
        "subs.toast.created": "Suscripción creada",
        "subs.form.editTitle": "Editar Suscripción",
        "subs.form.newTitle": "Nueva Suscripción",
        "subs.form.subtitle": "Pago o ingreso recurrente",
        "subs.form.mustBeLoggedIn": "Tenés que iniciar sesión.",
        "subs.form.expense": "Gasto",
        "subs.form.income": "Ingreso",
        "subs.form.name": "Nombre",
        "subs.form.namePlaceholder": "ej. Netflix",
        "subs.form.amount": "Monto",
        "subs.form.currency": "Moneda",
        "subs.form.vault": "Bóveda",
        "subs.form.category": "Categoría",
        "subs.form.none": "Ninguna",
        "subs.form.billingCycle": "Ciclo de facturación",
        "subs.form.every": "Cada",
        "subs.form.customIntervalDays": "Intervalo personalizado (días)",
        "subs.form.startDate": "Fecha de inicio",
        "subs.form.anchorDay": "Día ancla (opcional)",
        "subs.form.anchorHint": "Se cobra el día 31; los meses cortos usan el último día.",
        "subs.form.scheduleLifecycle": "Calendario y ciclo de vida",
        "subs.form.endDate": "Fecha de fin (opcional)",
        "subs.form.reminderDaysBefore": "Recordatorio (días antes)",
        "subs.form.trialEnds": "Fin de prueba (opcional)",
        "subs.form.trialAmount": "Monto de prueba",
        "subs.form.variableAmount": "Monto variable",
        "subs.form.variableAmountHint": "Te vamos a pedir que confirmes el monto cada ciclo",
        "subs.form.autoCharge": "Cobro automático",
        "subs.form.autoChargeHint": "Cobrar automáticamente en la fecha de vencimiento",
        "subs.form.extras": "Extras",
        "subs.form.fee": "Fee",
        "subs.form.feeNone": "Ninguno",
        "subs.form.feeFixed": "Fijo",
        "subs.form.value": "Valor",
        "subs.form.feeCurrencyHint": "El fee se cobra en la moneda de la suscripción ({currency}), igual que el monto.",
        "subs.form.cancelUrl": "URL de cancelación",
        "subs.form.notes": "Notas",
        "subs.form.icon": "Ícono",
        "subs.form.default": "Predeterminado",
        "subs.form.color": "Color",
        "subs.form.next3Charges": "Próximos 3 cargos",
        "subs.form.cancel": "Cancelar",
        "subs.form.saving": "Guardando...",
        "subs.form.saveChanges": "Guardar cambios",
        "subs.form.createSubscription": "Crear suscripción",
        "subs.row.includesFee": "Incluye fee — ver detalles",

        // Reports
        "reports.title": "Reportes",
        "reports.subtitle": "Resumen mensual de tus finanzas generado por IA.",
        "reports.regenerating": "Regenerando…",
        "reports.generating": "Generando…",
        "reports.regenerate": "Regenerar",
        "reports.generateReport": "Generar reporte",
        "reports.keyStoredEncrypted": "Tu clave se guarda cifrada y solo se usa para generar este reporte.",
        "reports.goToSettings": "Ir a Configuración",
        "reports.somethingWrong": "Algo salió mal.",
        "reports.networkError": "Error de red. Intentá de nuevo.",
        "reports.noReportYet": "Todavía no hay reporte",
        "reports.pickMonth": "Elegí un mes y generá tu primer resumen con IA.",
        "reports.income": "Ingresos",
        "reports.expenses": "Gastos",
        "reports.net": "Neto",
        "reports.netWorth": "Patrimonio neto",
        "reports.vsLastMonth": "{pct}% vs el mes pasado",
        "reports.adjustmentsNote": "Incluye {amount} en ajustes de saldo (no contados como gasto)",
        "reports.acrossVaultOne": "En {count} bóveda",
        "reports.acrossVaultMany": "En {count} bóvedas",
        "reports.monthSummary": "Resumen de {month}",
        "reports.topExpenseCategories": "Categorías principales de gasto",
        "reports.noExpensesMonth": "No hubo gastos este mes.",
        "reports.biggestExpenses": "Gastos más grandes",

        // Identity
        "identity.title": "Bóveda de Identidad",
        "identity.subtitle": "Guardá y gestioná tus documentos de identidad de forma segura.",
        "identity.privacyOn": "Privacidad Activa",
        "identity.privacyOff": "Privacidad Inactiva",
        "identity.addDocument": "Agregar Documento",
        "identity.totalDocuments": "Total de Documentos",
        "identity.withFiles": "Con Archivos",
        "identity.privacyMode": "Modo Privacidad",
        "identity.active": "Activo",
        "identity.inactive": "Inactivo",
        "identity.confirmDelete": "¿Seguro que querés eliminar este documento?",
        "identity.documentDeleted": "Documento eliminado",
        "identity.uploadNewDoc": "Subir un nuevo documento",
        "identity.accessLog": "Registro de Acceso",
        "identity.recentActivity": "Actividad reciente en tus documentos.",
        "identity.e2eTitle": "Cifrado de Extremo a Extremo",
        "identity.e2eDesc": "Todos los documentos en tu Bóveda de Identidad están cifrados en reposo y en tránsito. Solo vos podés acceder a tus archivos — ni siquiera el equipo de Nomadix puede leerlos.",
        "identity.protected": "Protegido",
        "identity.currentDevice": "Este dispositivo",

        // Travel
        "travel.title": "Viajes",
        "travel.subtitle": "Planificá y seguí tus aventuras.",
        "travel.newTrip": "Nuevo Viaje",
        "travel.totalTrips": "Viajes Totales",
        "travel.upcoming": "Próximos",
        "travel.budgetAllocated": "Presupuesto Asignado",
        "travel.addTrip": "Agregar Viaje",
        "travel.detail.backToTravel": "Volver a Viajes",
        "travel.detail.trip": "Viaje",
        "travel.detail.budget": "Presupuesto",
        "travel.detail.itinerary": "Itinerario",
        "travel.detail.addDay": "Agregar Día",
        "travel.detail.dayTitlePlaceholder": "Título del día (ej. Explorar el casco antiguo)",
        "travel.detail.descriptionOptional": "Descripción (opcional)",
        "travel.detail.estimatedCost": "Costo estimado",
        "travel.detail.adding": "Agregando...",
        "travel.detail.add": "Agregar",
        "travel.detail.noItineraryYet": "Todavía no hay itinerario",
        "travel.detail.addFirstDay": "Agregá tu primer día para empezar",
        "travel.detail.dayLabel": "Día {n}",
        "travel.detail.tbd": "A confirmar",
        "travel.status.planning": "Planificando",
        "travel.status.active": "Activo",
        "travel.status.completed": "Completado",
        "travel.status.inDays": "En {n}d",
        "travel.status.tbd": "A confirmar",
        "travel.modal.title": "Nuevo Viaje",
        "travel.modal.subtitle": "Planificá tu próxima aventura",
        "travel.modal.destination": "Destino",
        "travel.modal.destinationPlaceholder": "ej. Lisboa, Portugal",
        "travel.modal.destinationRequired": "El destino es obligatorio.",
        "travel.modal.startDate": "Fecha de inicio",
        "travel.modal.endDate": "Fecha de fin",
        "travel.modal.budgetOptional": "Presupuesto (opcional)",
        "travel.modal.cancel": "Cancelar",
        "travel.modal.creating": "Creando...",
        "travel.modal.createTrip": "Crear Viaje",
        "travel.toast.created": "Viaje creado",

        // Notification bell
        "bell.notifications": "Notificaciones",
        "bell.needsAttention": "Necesita atención",
        "bell.trialEnding": "Prueba por terminar",
        "bell.upcoming": "Próximos",
        "bell.allCaughtUp": "Estás al día.",
        "bell.markAllRead": "Marcar todo como leído",
        "bell.manageSubscriptions": "Gestionar suscripciones →",

        // Account Page
        "account.title": "Configuración de la Cuenta",
        "account.subtitle": "Gestiona tus datos personales y monedas de trabajo",
        "account.fullName": "Nombre Completo",
        "account.email": "Correo Electrónico",
        "account.timezone": "Zona Horaria",
        "account.baseCurrency": "Moneda Base",
        "account.saveChanges": "Guardar Cambios",
        "account.saving": "Guardando...",
        "account.saved": "Guardado",

        // Profile Page
        "profile.title": "Perfil Nómada",
        "profile.subtitle": "Tu perfil público, residencia fiscal y resumen",
        "profile.edit": "Editar Perfil",
        "profile.cancel": "Cancelar",
        "profile.save": "Guardar Cambios",
        "profile.occupation": "Profesión / Ocupación",
        "profile.bio": "Biografía / Descripción",
        "profile.taxResidency": "Residencia Fiscal / País",
        "profile.website": "Sitio Web / Portafolio",
        "profile.memberSince": "Miembro desde",
        "profile.activeVaults": "Bóvedas Activas",
        "profile.documents": "Documentos",
        "profile.plan": "Plan Actual",

        // Preferences Page
        "prefs.title": "Preferencias y Monedas",
        "prefs.subtitle": "Tasa de cambio en vivo y ajustes generales del sistema",
        "prefs.rateTitle": "Tasa de Cambio (USD / EUR)",
        "prefs.refreshRate": "Actualizar tasa en vivo",
        "prefs.refreshing": "Consultando...",
        "prefs.liveRateBadge": "Tasa de Mercado en Vivo",
        "prefs.manualRateBadge": "Tasa Manual Fija",
        "prefs.directRate": "Tasa Directa",
        "prefs.inverseRate": "Tasa Inversa",
        "prefs.manualToggle": "Fijar tasa de cambio manual",
        "prefs.manualDesc": "Sobrescribe la consulta automática para fijar tu propio tipo de cambio en conversiones.",
        "prefs.generalPrefs": "Ajustes Generales",
        "prefs.publicProfile": "Privacidad y Amigos",
        "prefs.publicProfileDesc": "Tu nombre de usuario, código de amigo y qué bóvedas aceptan transferencias.",
        "prefs.taxAlerts": "Alertas Fiscales",
        "prefs.taxAlertsDesc": "Avisos automáticos de límites de estancia o días de residencia fiscal.",
        "prefs.autoSync": "Sincronización Automática",
        "prefs.autoSyncDesc": "Actualizar transacciones y saldos en segundo plano periódicamente.",
        "prefs.darkMode": "Modo Oscuro",
        "prefs.darkModeDesc": "Activar tema visual oscuro en toda la interfaz de la aplicación.",
        "prefs.savedToast": "Preferencias actualizadas",

        // Security Page
        "security.title": "Seguridad y Autenticación",
        "security.subtitle": "Protege tus credenciales, contraseñas y sesiones",
        "security.status": "Cuenta Protegida",
        "security.changePass": "Cambiar Contraseña",
        "security.changePassDesc": "Actualiza tu clave para mantener seguras tus bóvedas financieras",
        "security.newPass": "Nueva Contraseña",
        "security.confirmPass": "Confirmar Nueva Contraseña",
        "security.updatePass": "Actualizar Contraseña",
        "security.activeSessions": "Sesiones Activas",
        "security.activeSessionsDesc": "Dispositivos autenticados actualmente",
        "security.signOutOthers": "Cerrar sesión en otros dispositivos",
        "security.passUpdatedToast": "Contraseña actualizada exitosamente",

        // Notifications Page
        "notif.title": "Notificaciones y Alertas",
        "notif.subtitle": "Elige cuándo y cómo recibir avisos de facturas y saldos",
        "notif.push": "Notificaciones Push del Navegador",
        "notif.pushDesc": "Recibe alertas en tiempo real incluso con la app en segundo plano",
        "notif.enablePush": "Activar Notificaciones",
        "notif.subsSection": "Suscripciones y Vencimientos",
        "notif.sub1d": "Aviso 24 horas antes",
        "notif.sub3d": "Aviso con 3 días de anticipación",
        "notif.subPrice": "Cambios de precio y fin de pruebas gratis",
        "notif.vaultsSection": "Bóvedas y Saldos",
        "notif.vaultLow": "Aviso de saldo bajo en bóvedas",
        "notif.vaultLowDesc": "Avisar cuando una bóveda no tenga saldo para cargos recurrentes",
        "notif.receivableReminder": "Recordatorio de cuentas por cobrar",
        "notif.receivableReminderDesc": "Avisar cuando una cuenta por cobrar esté por vencer o vencida",
        "notif.emailSection": "Entrega por Correo",
        "notif.emailWeekly": "Resumen semanal de gastos",

        // Billing Page
        "billing.title": "Facturación y Suscripción",
        "billing.subtitle": "Administra tu membresía Nomadix Pro, ciclo de facturación y recibos",
        "billing.planName": "Plan Nomadix Premium",
        "billing.active": "Activo",
        "billing.monthly": "Mensual",
        "billing.annual": "Anual",
        "billing.saveBadge": "Ahorra 25%",
        "billing.manage": "Gestionar Plan",
        "billing.included": "Incluido en tu plan",
        "billing.usage": "Uso de la Cuenta",
        "billing.receipts": "Recibos y Facturas",

        // Language Page
        "lang.title": "Idioma y Configuración Regional",
        "lang.subtitle": "Personaliza el idioma del sistema, formato de fecha y separadores numéricos",
        "lang.preview": "Vista Previa de Formato Regional en Vivo",
        "lang.datePreview": "Fecha Actual",
        "lang.numberPreview": "Muestra de Gasto",
        "lang.firstDayPreview": "Primer día de la semana",
        "lang.displayLang": "Idioma de la Interfaz",
        "lang.formatsSection": "Formatos de Fecha y Números",
        "lang.dateFormat": "Formato de Fecha",
        "lang.numberFormat": "Separador Numérico y Decimal",
        "lang.firstDay": "Primer Día de la Semana",
        "lang.monday": "Lunes (Monday)",
        "lang.sunday": "Domingo (Sunday)",
        "lang.save": "Guardar Preferencias",

        // Support Page
        "support.title": "Ayuda y Soporte",
        "support.subtitle": "Preguntas frecuentes, contacto con el equipo de soporte y estado",
        "support.docs": "Documentación",
        "support.community": "Comunidad Nómada",
        "support.status": "Estado del Sistema",
        "support.faq": "Preguntas Frecuentes",
        "support.contact": "Contactar con Soporte",
        "support.category": "Categoría",
        "support.priority": "Prioridad",
        "support.subject": "Asunto",
        "support.message": "Mensaje",
        "support.send": "Enviar Ticket",

        // Data Page
        "data.title": "Gestión de Datos y Privacidad",
        "data.subtitle": "Exporta tu historial de transacciones, copias de seguridad y control de cuenta",
        "data.exportSection": "Exportar Datos",
        "data.jsonTitle": "Copia de Seguridad Completa (JSON)",
        "data.jsonDesc": "Descarga todas tus bóvedas, suscripciones, documentos y transacciones en JSON.",
        "data.downloadJson": "Descargar JSON",
        "data.csvTitle": "Planilla de Transacciones (CSV)",
        "data.csvDesc": "Exporta tus gastos, transferencias y comisiones para contabilidad, Excel o impuestos.",
        "data.downloadCsv": "Descargar CSV",
        "data.danger": "Zona de Peligro",
        "data.deleteTitle": "Eliminar Cuenta y Datos Personales",
        "data.deleteDesc": "Borra permanentemente tus bóvedas, transacciones y documentos. Acción irreversible.",
        "data.deleteBtn": "Eliminar Datos de Cuenta",

        // Friends
        "friends.title": "Amigos",
        "friends.subtitle": "Agrega amigos para transferir dinero y compartir gastos.",
        "friends.searchPlaceholder": "Buscar por @usuario o código NMDX-XXXX",
        "friends.searchButton": "Buscar",
        "friends.searchHint": "Nunca podés buscar a alguien por su email.",
        "friends.searchNoResults": "No se encontró ningún usuario con ese dato.",
        "friends.sendRequest": "Agregar",
        "friends.requestSent": "Solicitud enviada",
        "friends.tabFriends": "Amigos",
        "friends.tabRequests": "Solicitudes",
        "friends.tabBalances": "Balances",
        "friends.balancesComingSoon": "Los balances de gastos compartidos llegan en la próxima fase.",
        "friends.noFriendsYet": "Todavía no tenés amigos agregados",
        "friends.noFriendsYetDesc": "Buscá a alguien por su usuario o código de amigo para empezar.",
        "friends.noRequests": "No tenés solicitudes pendientes",
        "friends.incomingRequests": "Te escribieron",
        "friends.outgoingRequests": "Enviadas por vos",
        "friends.accept": "Aceptar",
        "friends.decline": "Rechazar",
        "friends.cancelRequest": "Cancelar",
        "friends.remove": "Eliminar amigo",
        "friends.block": "Bloquear",
        "friends.unblock": "Desbloquear",
        "friends.confirmRemove": "¿Eliminar a este amigo?",
        "friends.confirmBlock": "¿Bloquear a este usuario? No podrá volver a escribirte.",
        "friends.outstandingBalance": "Tenés un balance pendiente con este amigo. Saldalo antes de eliminarlo, o forzá la eliminación (el balance se anula).",
        "friends.forceRemove": "Eliminar de todas formas",
        "friends.since": "Amigos desde {date}",
        "friends.you": "Vos",
        "friends.actionFailed": "No se pudo completar la acción",

        // Settings > Privacy & Friends (identity)
        "socialPrivacy.title": "Privacidad y Amigos",
        "socialPrivacy.subtitle": "Tu identidad pública y quién puede encontrarte.",
        "socialPrivacy.identitySection": "Tu Identidad",
        "socialPrivacy.usernameLabel": "Nombre de usuario",
        "socialPrivacy.usernamePlaceholder": "tu_usuario",
        "socialPrivacy.usernameHint": "3-20 caracteres: letras, números y guión bajo. Podés cambiarlo cada 30 días.",
        "socialPrivacy.usernameSave": "Guardar usuario",
        "socialPrivacy.usernameCooldown": "Podrás cambiar tu usuario de nuevo en {days} días.",
        "socialPrivacy.usernameTaken": "Ese nombre de usuario ya está en uso.",
        "socialPrivacy.usernameSaved": "Nombre de usuario actualizado",
        "socialPrivacy.friendCodeLabel": "Tu código de amigo",
        "socialPrivacy.friendCodeHint": "Compartilo para que alguien te agregue sin buscar tu usuario.",
        "socialPrivacy.friendCodeCopy": "Copiar",
        "socialPrivacy.friendCodeCopied": "Código copiado",
        "socialPrivacy.friendCodeRegenerate": "Generar nuevo código",
        "socialPrivacy.friendCodeRegenerateHint": "El código anterior deja de funcionar de inmediato.",
        "socialPrivacy.friendCodeRegenerated": "Nuevo código generado",
        "socialPrivacy.discoverableLabel": "Permitir que me encuentren",
        "socialPrivacy.discoverableDesc": "Si está apagado, nadie puede encontrarte por usuario ni por código, ni enviarte solicitudes de amistad.",
        "socialPrivacy.vaultsSection": "Transferencias a mis bóvedas",
        "socialPrivacy.vaultsComingSoon": "La privacidad por bóveda (quién puede transferirte dinero) llega en la próxima fase. Tu saldo nunca es visible para nadie más, bajo ninguna circunstancia.",
        "socialPrivacy.balanceNeverShown": "Tu saldo nunca se muestra a tus amigos.",
        "socialPrivacy.vaultPolicyNobody": "Cerrada",
        "socialPrivacy.vaultPolicyNobodyDesc": "Nadie puede transferirte dinero a esta bóveda.",
        "socialPrivacy.vaultPolicyFriends": "Todos mis amigos",
        "socialPrivacy.vaultPolicyFriendsDesc": "Cualquier amigo aceptado puede transferirte a esta bóveda.",
        "socialPrivacy.vaultPolicyAllowlist": "Amigos seleccionados",
        "socialPrivacy.vaultPolicyAllowlistDesc": "Solo los amigos que elijas pueden transferirte a esta bóveda.",
        "socialPrivacy.selectFriends": "Elegir amigos",
        "socialPrivacy.noFriendsToSelect": "Todavía no tenés amigos para seleccionar.",
        "socialPrivacy.notePlaceholder": "Nota para quien te transfiera (opcional)",
        "socialPrivacy.policySaved": "Privacidad de la bóveda actualizada",
        "socialPrivacy.savePolicy": "Guardar",

        // Transfers
        "transfer.send": "Enviar",
        "transfer.sendTo": "Enviar a {name}",
        "transfer.fromVault": "Desde tu bóveda",
        "transfer.toVault": "A la bóveda de {name}",
        "transfer.selectVault": "Seleccioná una bóveda",
        "transfer.noOpenVaults": "{name} no tiene bóvedas abiertas a transferencias tuyas.",
        "transfer.amount": "Monto",
        "transfer.includeFee": "¿Incluye comisión?",
        "transfer.totalDebited": "Se descontará {amount} de tu bóveda",
        "transfer.note": "Nota (opcional)",
        "transfer.willReceive": "{name} recibirá aproximadamente {amount}",
        "transfer.confirm": "Confirmar envío",
        "transfer.sent": "Transferencia enviada",
        "transfer.sendFailed": "No se pudo enviar la transferencia",
        "transfer.insufficientFunds": "Fondos insuficientes en la bóveda de origen",
        "transfer.notAllowed": "Esa transferencia no está permitida",
        "transfer.recentTitle": "Transferencias recientes",
        "transfer.noneYet": "Todavía no hay transferencias",
        "transfer.returnAction": "Devolver",
        "transfer.returnConfirm": "¿Devolver esta transferencia?",
        "transfer.returned": "Transferencia devuelta",
        "transfer.returnFailed": "No se pudo devolver la transferencia",
        "transfer.reversibleFor": "Se puede devolver por {hours}h {minutes}m más",
        "transfer.windowExpired": "Ya no se puede devolver",
        "transfer.reversedBadge": "Devuelta",
        "transfer.sentTo": "Enviaste a {name}",
        "transfer.receivedFrom": "Recibiste de {name}",

        // Shared vaults
        "sharedVault.badge": "Compartida",
        "sharedVault.shareAction": "Compartir bóveda",
        "sharedVault.leaveAction": "Salir de la bóveda",
        "sharedVault.dissolveAction": "Disolver bóveda compartida",
        "sharedVault.selectFriend": "Elegí un amigo para compartir esta bóveda",
        "sharedVault.invited": "Invitación enviada",
        "sharedVault.inviteFailed": "No se pudo enviar la invitación",
        "sharedVault.pendingInvite": "{name} te invitó a compartir \"{vault}\"",
        "sharedVault.accept": "Aceptar",
        "sharedVault.decline": "Rechazar",
        "sharedVault.accepted": "Ahora compartís esta bóveda",
        "sharedVault.declined": "Invitación rechazada",
        "sharedVault.leftVault": "Saliste de la bóveda compartida",
        "sharedVault.leaveFailed": "No se pudo salir de la bóveda",
        "sharedVault.confirmLeave": "¿Salir de esta bóveda compartida?",
        "sharedVault.with": "Compartida con {name}",

        // Splits
        "split.action": "Dividir con un amigo",
        "split.modalTitle": "Dividir gasto",
        "split.selectFriend": "Amigo",
        "split.modeEqual": "50 / 50",
        "split.modeAmount": "Monto",
        "split.modePercent": "Porcentaje",
        "split.theyOwe": "{name} te debe {amount}",
        "split.youOwe": "Le debés {amount} a {name}",
        "split.confirm": "Crear división",
        "split.created": "Gasto dividido",
        "split.createFailed": "No se pudo dividir el gasto",
        "split.badge": "Dividido",
        "split.void": "Anular división",
        "split.voided": "División anulada",
        "split.reject": "No es mío",
        "split.rejected": "División rechazada",
        "split.alreadySettled": "Esta división ya fue saldada",
        "split.notSharable": "Esta bóveda ya es compartida, no se puede dividir con otra persona.",

        // Balances (Friends > Balances tab)
        "balances.title": "Balances con amigos",
        "balances.allSettled": "Estás al día con todos tus amigos",
        "balances.owesYou": "{name} te debe",
        "balances.youOwe": "Le debés a {name}",
        "balances.settleUp": "Saldar",
        "balances.settleUpTitle": "Saldar con {name}",
        "balances.settleAmount": "Monto a saldar",
        "balances.settleFromVault": "Desde tu bóveda",
        "balances.settleToVault": "A la bóveda de {name}",
        "balances.settled": "Balance saldado",
        "balances.settleFailed": "No se pudo saldar el balance",
        "balances.nothingToSettle": "No hay nada que saldar con este amigo",

        // Common (shared across small forms/modals)
        "common.cancel": "Cancelar",
        "common.confirm": "Confirmar",
        "common.edit": "Editar",
        "common.save": "Guardar",
        "common.saving": "Guardando...",
        "common.optional": "opcional",

        // Receivables (Pendiente por cobrar)
        "nav.receivables": "Por Cobrar",
        "receivables.title": "Pendiente por Cobrar",
        "receivables.subtitle": "Dinero facturado que tus clientes aún no te han pagado.",
        "receivables.mustBeLoggedIn": "Debes iniciar sesión para ver tus cuentas por cobrar.",
        "receivables.tablesNotSetUp": "Esta función aún no está configurada. Contacta soporte.",
        "receivables.new": "Nueva Cuenta",
        "receivables.manageClients": "Clientes",
        "receivables.noResults": "No hay cuentas que coincidan con este filtro.",
        "receivables.emptyVaultTitle": "Todavía no tienes una bóveda de cobro",
        "receivables.emptyVaultBody": "Crea una bóveda de tipo \"Pendiente por Cobrar\" desde Bóvedas para empezar a registrar cuentas por cobrar.",
        "receivables.emptyVaultCta": "Ir a Bóvedas",
        "receivables.stats.outstanding": "Pendiente",
        "receivables.stats.overdue": "Vencido",
        "receivables.stats.overdueHint": "Requiere seguimiento",
        "receivables.stats.dueThisMonth": "Vence este mes",
        "receivables.stats.collectedThisMonth": "Cobrado este mes",
        "receivables.filter.all": "Todas",
        "receivables.filter.pending": "Pendientes",
        "receivables.filter.overdue": "Vencidas",
        "receivables.filter.paid": "Cobradas",
        "receivables.newTitle": "Nueva Cuenta por Cobrar",
        "receivables.editTitle": "Editar Cuenta por Cobrar",
        "receivables.newSubtitle": "Registra dinero facturado que estás esperando cobrar",
        "receivables.field.vault": "Bóveda",
        "receivables.field.client": "Cliente",
        "receivables.field.description": "Descripción",
        "receivables.field.amount": "Monto",
        "receivables.field.currency": "Moneda",
        "receivables.field.issueDate": "Fecha de Emisión",
        "receivables.field.expectedDate": "Fecha Esperada de Pago",
        "receivables.field.reminder": "Recordatorio de Cobro",
        "receivables.field.reminderHint": "Avisa antes de la fecha esperada",
        "receivables.field.reminderDaysSuffix": "días antes",
        "receivables.field.notes": "Notas",
        "receivables.toast.created": "Cuenta por cobrar creada",
        "receivables.toast.updated": "Cuenta por cobrar actualizada",
        "receivables.toast.collected": "Cobro registrado",
        "receivables.toast.canceled": "Cuenta por cobrar cancelada",
        "receivables.detail.outstanding": "Pendiente",
        "receivables.detail.collected": "Cobrado",
        "receivables.detail.collectedOfTotal": "cobrado de",
        "receivables.detail.overdueWarning": "Esta cuenta está vencida.",
        "receivables.detail.collectAction": "Registrar Cobro",
        "receivables.detail.cancelAction": "Cancelar Cuenta",
        "receivables.collect.title": "Registrar Cobro",
        "receivables.collect.outstanding": "Pendiente",
        "receivables.collect.destinationVault": "Bóveda de Destino",
        "receivables.collect.amountToCollect": "Monto a Cobrar",
        "receivables.collect.partialHint": "Se registrará como un cobro parcial.",
        "receivables.collect.exchangeRate": "Tasa de Cambio",
        "receivables.collect.rateHint": "Monedas distintas -- indica la tasa de conversión.",
        "receivables.collect.noLiquidVaults": "Necesitas al menos una bóveda líquida (Ahorros, Corriente o Efectivo) para recibir el cobro.",
        "receivables.collect.selectVault": "Selecciona una bóveda de destino.",
        "receivables.collect.invalidAmount": "Ingresa un monto válido.",
        "receivables.collect.exceedsOutstanding": "El monto supera lo pendiente.",
        "receivables.collect.invalidRate": "Ingresa una tasa de cambio válida.",
        "receivables.collect.confirm": "Confirmar Cobro",
        "receivables.clients.title": "Clientes",
        "receivables.clients.subtitle": "Personas o empresas que te deben dinero.",
        "receivables.clients.addPlaceholder": "Nombre del cliente…",
        "receivables.clients.empty": "Todavía no tienes clientes.",
        "receivables.clients.archive": "Archivar",
        "receivables.clients.unarchive": "Restaurar",
        "receivables.clients.archived": "Archivados",
    },
    en: {
        // Navigation
        "nav.dashboard": "Dashboard",
        "nav.vaults": "Vaults",
        "nav.expenses": "Expenses",
        "nav.subscriptions": "Subscriptions",
        "nav.reports": "Reports",
        "nav.friends": "Friends",
        "nav.identity": "Identity",
        "nav.travel": "Travel",
        "nav.settings": "Settings",
        "nav.signOut": "Sign Out",
        "nav.backToApp": "Back to app",

        // Settings Navigation
        "settings.account": "Account",
        "settings.profile": "Profile",
        "settings.privacy": "Privacy & Friends",
        "settings.preferences": "Preferences",
        "settings.categories": "Categories",
        "settings.ai": "AI Assistant",
        "settings.data": "Data",
        "settings.security": "Security",
        "settings.notifications": "Notifications",
        "settings.billing": "Billing",
        "settings.language": "Language & Region",
        "settings.support": "Support",

        // Dashboard
        "dashboard.title": "Dashboard",
        "dashboard.welcome": "Welcome back, {name}.",
        "dashboard.totalBalance": "Total Combined Balance",
        "dashboard.active": "Active",
        "dashboard.incomeVsExpenses": "Income vs Expenses",
        "dashboard.last4Weeks": "Last 4 weeks overview",
        "dashboard.week": "Week",
        "dashboard.income": "Income",
        "dashboard.expenses": "Expenses",
        "dashboard.checking": "Checking",
        "dashboard.savings": "Savings",
        "dashboard.cash": "Cash",
        "dashboard.transactions": "Transactions",
        "dashboard.noTransactions": "No transactions yet. Add one!",
        "dashboard.viewAllTransactions": "View All Transactions",

        // Vaults
        "vaults.title": "Vaults",
        "vaults.subtitle": "Manage your multi-currency financial vaults.",
        "vaults.transaction": "Transaction",
        "vaults.newVault": "New Vault",
        "vaults.totalAcrossAll": "Total Across All Vaults",
        "vaults.recentActivity": "Recent Activity",
        "vaults.filterAll": "All",
        "vaults.filterIncome": "Income",
        "vaults.filterExpense": "Expense",
        "vaults.filterTransfer": "Transfer",
        "vaults.filterByCategory": "Filter by category",
        "vaults.categories": "Categories",
        "vaults.categoriesCount": "Categories ({count})",
        "vaults.search": "Search…",
        "vaults.clearFilter": "Clear filter",
        "vaults.balance": "Balance",
        "vaults.pendingCollection": "Pending Collection",
        "vaults.projectedTotal": "Projected Total",
        "vaults.receivableAccountsCount": "{count} accounts",
        "vaults.receivableAccountsOverdue": "{count} accounts · {overdue} overdue",
        "vaults.type.savings": "Savings",
        "vaults.type.checking": "Checking",
        "vaults.type.cash": "Cash",
        "vaults.type.receivable": "Pending Collection",
        "vaults.noResults": "No results.",
        "vaults.colDate": "Date",
        "vaults.colDescription": "Description",
        "vaults.colVault": "Vault",
        "vaults.colCategory": "Category",
        "vaults.colAmount": "Amount",
        "vaults.noTransactionsFound": "No transactions found.",
        "vaults.loading": "Loading...",
        "vaults.loadMore": "Load more activity",
        "vaults.noMore": "No more activity.",
        "vaults.myVaults": "Your Vaults",
        "vaults.viewOptions": "View options",
        "vaults.visibleLimitTitle": "Visible vaults",
        "vaults.visibleLimitDesc": "Default amount displayed",
        "vaults.optionOneRow": "1 row (4 vaults)",
        "vaults.optionTwoRows": "2 rows (8 vaults)",
        "vaults.optionThreeRows": "3 rows (12 vaults)",
        "vaults.optionAll": "Show all",
        "vaults.defaultBadge": "Default",
        "vaults.showMore": "Show {count} more",
        "vaults.showLess": "Show less",

        // Expenses
        "expenses.title": "Expenses",
        "expenses.subtitle": "Analyze your spending across categories and time.",
        "expenses.converting": "Converting…",
        "expenses.dateRange": "Date range",
        "expenses.from": "From",
        "expenses.to": "To",
        "expenses.vault": "Vault",
        "expenses.vaultFilter": "Vault filter",
        "expenses.allVaults": "All vaults",
        "expenses.totalSpent": "Total spent",
        "expenses.topCategory": "Top category: {category} ({pct}%)",
        "expenses.periodVsPeriod": "Period vs period",
        "expenses.comparedToPrevious": "Compared to previous {days} days",
        "expenses.setDateRange": "Set a date range to compare",
        "expenses.spendingOverTime": "Spending over time",
        "expenses.categoryShare": "Category share",
        "expenses.topCategoriesBySpend": "Top categories by spend",
        "expenses.spendByCategory": "Spend by category",
        "expenses.totalDistribution": "Total and distribution for the selected filters",
        "expenses.colCategory": "Category",
        "expenses.colTotal": "Total",
        "expenses.noExpensesFound": "No expenses found for the selected filters.",
        "expenses.highlights": "Highlights",
        "expenses.monthlyAverage": "Monthly average",
        "expenses.largestExpense": "Largest expense",
        "expenses.unknown": "Unknown",
        "expenses.totalTransactions": "Total transactions",
        "expenses.filteredExpenses": "Filtered expenses in the selected range",

        // Subscriptions
        "subs.title": "Subscriptions",
        "subs.subtitle": "Recurring payments and income",
        "subs.new": "New Subscription",
        "subs.filterAll": "All",
        "subs.filterActive": "Active",
        "subs.filterPaused": "Paused",
        "subs.filterCanceled": "Canceled",
        "subs.allVaults": "All vaults",
        "subs.colSubscription": "Subscription",
        "subs.colCycle": "Cycle",
        "subs.colVault": "Vault",
        "subs.colNextCharge": "Next charge",
        "subs.colAmount": "Amount",
        "subs.emptyTitle": "No subscriptions yet",
        "subs.emptySubtitle": "Track Netflix, rent, gym, or any recurring income.",
        "subs.mustBeLoggedIn": "You must be logged in to view subscriptions.",
        "subs.tablesNotSetUp": "The subscriptions tables aren't set up yet. Run supabase/schema.sql in the Supabase SQL editor, then reload the API schema (Settings → API → Reload schema).",
        "subs.stats.monthlyCost": "Monthly cost",
        "subs.stats.normalized": "Normalized across all cycles",
        "subs.stats.annualized": "Annualized",
        "subs.stats.activeOne": "{count} active subscription",
        "subs.stats.activeMany": "{count} active subscriptions",
        "subs.stats.next30Days": "Next 30 days",
        "subs.stats.chargeOne": "{count} charge",
        "subs.stats.chargeMany": "{count} charges",
        "subs.stats.recurringIncome": "Recurring income",
        "subs.stats.perMonth": "/mo",
        "subs.stats.incomeSub": "Salary, rent, freelance & more",
        "subs.detail.summaryAmount": "Amount",
        "subs.detail.summaryVault": "Vault",
        "subs.detail.summaryCategory": "Category",
        "subs.detail.summaryNextCharge": "Next charge",
        "subs.detail.summaryMonthlyEq": "Monthly eq.",
        "subs.detail.summaryAnnualized": "Annualized",
        "subs.detail.subtotal": "Subtotal",
        "subs.detail.fee": "Fee",
        "subs.detail.total": "Total",
        "subs.detail.chargeNow": "Charge now",
        "subs.detail.skip": "Skip this cycle",
        "subs.detail.pause": "Pause",
        "subs.detail.resume": "Resume",
        "subs.detail.cancel": "Cancel subscription",
        "subs.detail.confirmCancel": "Confirm cancel?",
        "subs.detail.edit": "Edit",
        "subs.detail.openCancelUrl": "Open cancellation page",
        "subs.detail.paymentHistory": "Payment history",
        "subs.detail.noCharges": "No charges yet.",
        "subs.detail.inclFee": "incl. {amount} fee",
        "subs.confirm.title": "Confirm charge",
        "subs.confirm.dueLabel": "{name} · Due {date}",
        "subs.confirm.amount": "Amount",
        "subs.confirm.vaultPrefix": "Vault:",
        "subs.confirm.note": "Note (optional)",
        "subs.confirm.willDeductFrom": "This will deduct {amount} from {vault}.",
        "subs.confirm.willAddTo": "This will add {amount} to {vault}.",
        "subs.confirm.theVault": "the vault",
        "subs.confirm.skip": "Skip this cycle",
        "subs.confirm.processing": "Processing...",
        "subs.confirm.confirmCharge": "Confirm charge",
        "subs.confirm.invalidAmount": "Enter a valid amount.",
        "subs.widget.title": "Upcoming charges",
        "subs.widget.next30days": "Next 30 days",
        "subs.widget.viewAll": "View all",
        "subs.widget.confirm": "Confirm",
        "subs.widget.shortfall": "Balance may drop below {zero} on {date}",
        "subs.widget.empty": "No upcoming charges in the next 30 days.",
        "subs.widget.addSubscription": "Add a subscription →",
        "subs.toast.charged": "{name} charged",
        "subs.toast.skippedNamed": "{name} skipped this cycle",
        "subs.toast.skipped": "Skipped this cycle",
        "subs.toast.paused": "Subscription paused",
        "subs.toast.resumed": "Subscription resumed",
        "subs.toast.canceled": "Subscription canceled",
        "subs.toast.updated": "Subscription updated",
        "subs.toast.created": "Subscription created",
        "subs.form.editTitle": "Edit Subscription",
        "subs.form.newTitle": "New Subscription",
        "subs.form.subtitle": "Recurring payment or income",
        "subs.form.mustBeLoggedIn": "You must be logged in.",
        "subs.form.expense": "Expense",
        "subs.form.income": "Income",
        "subs.form.name": "Name",
        "subs.form.namePlaceholder": "e.g. Netflix",
        "subs.form.amount": "Amount",
        "subs.form.currency": "Currency",
        "subs.form.vault": "Vault",
        "subs.form.category": "Category",
        "subs.form.none": "None",
        "subs.form.billingCycle": "Billing cycle",
        "subs.form.every": "Every",
        "subs.form.customIntervalDays": "Custom interval (days)",
        "subs.form.startDate": "Start date",
        "subs.form.anchorDay": "Anchor day (optional)",
        "subs.form.anchorHint": "Charged on day 31; short months use the last day.",
        "subs.form.scheduleLifecycle": "Schedule & lifecycle",
        "subs.form.endDate": "End date (optional)",
        "subs.form.reminderDaysBefore": "Reminder (days before)",
        "subs.form.trialEnds": "Trial ends (optional)",
        "subs.form.trialAmount": "Trial amount",
        "subs.form.variableAmount": "Variable amount",
        "subs.form.variableAmountHint": "You'll be asked to confirm the amount each cycle",
        "subs.form.autoCharge": "Auto-charge",
        "subs.form.autoChargeHint": "Charge automatically on the due date",
        "subs.form.extras": "Extras",
        "subs.form.fee": "Fee",
        "subs.form.feeNone": "None",
        "subs.form.feeFixed": "Fixed",
        "subs.form.value": "Value",
        "subs.form.feeCurrencyHint": "Fee is charged in the subscription's currency ({currency}), same as the amount.",
        "subs.form.cancelUrl": "Cancellation URL",
        "subs.form.notes": "Notes",
        "subs.form.icon": "Icon",
        "subs.form.default": "Default",
        "subs.form.color": "Color",
        "subs.form.next3Charges": "Next 3 charges",
        "subs.form.cancel": "Cancel",
        "subs.form.saving": "Saving...",
        "subs.form.saveChanges": "Save changes",
        "subs.form.createSubscription": "Create subscription",
        "subs.row.includesFee": "Includes fee — see details",

        // Reports
        "reports.title": "Reports",
        "reports.subtitle": "AI-generated monthly summary of your finances.",
        "reports.regenerating": "Regenerating…",
        "reports.generating": "Generating…",
        "reports.regenerate": "Regenerate",
        "reports.generateReport": "Generate report",
        "reports.keyStoredEncrypted": "Your key is stored encrypted and used only to generate this report.",
        "reports.goToSettings": "Go to Settings",
        "reports.somethingWrong": "Something went wrong.",
        "reports.networkError": "Network error. Please try again.",
        "reports.noReportYet": "No report yet",
        "reports.pickMonth": "Pick a month and generate your first AI summary.",
        "reports.income": "Income",
        "reports.expenses": "Expenses",
        "reports.net": "Net",
        "reports.netWorth": "Net worth",
        "reports.vsLastMonth": "{pct}% vs last month",
        "reports.adjustmentsNote": "Includes {amount} in balance adjustments (not counted as spending)",
        "reports.acrossVaultOne": "Across {count} vault",
        "reports.acrossVaultMany": "Across {count} vaults",
        "reports.monthSummary": "{month} summary",
        "reports.topExpenseCategories": "Top expense categories",
        "reports.noExpensesMonth": "No expenses this month.",
        "reports.biggestExpenses": "Biggest expenses",

        // Identity
        "identity.title": "Identity Vault",
        "identity.subtitle": "Securely store and manage your identity documents.",
        "identity.privacyOn": "Privacy On",
        "identity.privacyOff": "Privacy Off",
        "identity.addDocument": "Add Document",
        "identity.totalDocuments": "Total Documents",
        "identity.withFiles": "With Files",
        "identity.privacyMode": "Privacy Mode",
        "identity.active": "Active",
        "identity.inactive": "Inactive",
        "identity.confirmDelete": "Are you sure you want to delete this document?",
        "identity.documentDeleted": "Document deleted",
        "identity.uploadNewDoc": "Upload a new ID document",
        "identity.accessLog": "Access Log",
        "identity.recentActivity": "Recent activity on your documents.",
        "identity.e2eTitle": "End-to-End Encryption",
        "identity.e2eDesc": "All documents in your Identity Vault are encrypted at rest and in transit. Only you can access your files — not even the Nomadix team can read them.",
        "identity.protected": "Protected",
        "identity.currentDevice": "Current Device",

        // Travel
        "travel.title": "Travel",
        "travel.subtitle": "Plan and track your adventures.",
        "travel.newTrip": "New Trip",
        "travel.totalTrips": "Total Trips",
        "travel.upcoming": "Upcoming",
        "travel.budgetAllocated": "Budget Allocated",
        "travel.addTrip": "Add Trip",
        "travel.detail.backToTravel": "Back to Travel",
        "travel.detail.trip": "Trip",
        "travel.detail.budget": "Budget",
        "travel.detail.itinerary": "Itinerary",
        "travel.detail.addDay": "Add Day",
        "travel.detail.dayTitlePlaceholder": "Day title (e.g. Explore Old Town)",
        "travel.detail.descriptionOptional": "Description (optional)",
        "travel.detail.estimatedCost": "Estimated cost",
        "travel.detail.adding": "Adding...",
        "travel.detail.add": "Add",
        "travel.detail.noItineraryYet": "No itinerary yet",
        "travel.detail.addFirstDay": "Add your first day to get started",
        "travel.detail.dayLabel": "Day {n}",
        "travel.detail.tbd": "TBD",
        "travel.status.planning": "Planning",
        "travel.status.active": "Active",
        "travel.status.completed": "Completed",
        "travel.status.inDays": "In {n}d",
        "travel.status.tbd": "TBD",
        "travel.modal.title": "New Trip",
        "travel.modal.subtitle": "Plan your next adventure",
        "travel.modal.destination": "Destination",
        "travel.modal.destinationPlaceholder": "e.g. Lisbon, Portugal",
        "travel.modal.destinationRequired": "Destination is required.",
        "travel.modal.startDate": "Start Date",
        "travel.modal.endDate": "End Date",
        "travel.modal.budgetOptional": "Budget (optional)",
        "travel.modal.cancel": "Cancel",
        "travel.modal.creating": "Creating...",
        "travel.modal.createTrip": "Create Trip",
        "travel.toast.created": "Trip created",

        // Notification bell
        "bell.notifications": "Notifications",
        "bell.needsAttention": "Needs attention",
        "bell.trialEnding": "Trial ending",
        "bell.upcoming": "Upcoming",
        "bell.allCaughtUp": "You're all caught up.",
        "bell.markAllRead": "Mark all as read",
        "bell.manageSubscriptions": "Manage subscriptions →",

        // Account Page
        "account.title": "Account Settings",
        "account.subtitle": "Manage your personal information and working currencies",
        "account.fullName": "Full Name",
        "account.email": "Email Address",
        "account.timezone": "Timezone",
        "account.baseCurrency": "Base Currency",
        "account.saveChanges": "Save Changes",
        "account.saving": "Saving...",
        "account.saved": "Saved",

        // Profile Page
        "profile.title": "Nomad Profile",
        "profile.subtitle": "Your public profile overview, tax status, and account stats",
        "profile.edit": "Edit Profile",
        "profile.cancel": "Cancel",
        "profile.save": "Save Changes",
        "profile.occupation": "Occupation / Title",
        "profile.bio": "Bio / Description",
        "profile.taxResidency": "Tax Residency / Country",
        "profile.website": "Website / Portfolio",
        "profile.memberSince": "Member since",
        "profile.activeVaults": "Active Vaults",
        "profile.documents": "Vault Documents",
        "profile.plan": "Current Plan",

        // Preferences Page
        "prefs.title": "Preferences & Currencies",
        "prefs.subtitle": "Live market exchange rates and system-wide preferences",
        "prefs.rateTitle": "Exchange Rate (USD / EUR)",
        "prefs.refreshRate": "Refresh live rate",
        "prefs.refreshing": "Refreshing...",
        "prefs.liveRateBadge": "Live Market Rate",
        "prefs.manualRateBadge": "Manual Fixed Rate",
        "prefs.directRate": "Direct Rate",
        "prefs.inverseRate": "Inverse Rate",
        "prefs.manualToggle": "Enable custom manual rate",
        "prefs.manualDesc": "Override live market rates to lock in a specific rate from transfers or withdrawals.",
        "prefs.generalPrefs": "General Preferences",
        "prefs.publicProfile": "Privacy & Friends",
        "prefs.publicProfileDesc": "Your username, friend code, and which vaults accept transfers.",
        "prefs.taxAlerts": "Tax Residency Alerts",
        "prefs.taxAlertsDesc": "Automatic warnings regarding duration limits for fiscal residency.",
        "prefs.autoSync": "Automatic Sync",
        "prefs.autoSyncDesc": "Periodically refresh transactions and vault balances in the background.",
        "prefs.darkMode": "Dark Mode",
        "prefs.darkModeDesc": "Enable the dark visual theme across the entire application interface.",
        "prefs.savedToast": "Preferences updated",

        // Security Page
        "security.title": "Security & Authentication",
        "security.subtitle": "Protect your credentials, passwords, and active sessions",
        "security.status": "Account Protected",
        "security.changePass": "Change Password",
        "security.changePassDesc": "Update your password to keep your financial vaults secure",
        "security.newPass": "New Password",
        "security.confirmPass": "Confirm New Password",
        "security.updatePass": "Update Password",
        "security.activeSessions": "Active Sessions",
        "security.activeSessionsDesc": "Devices currently authenticated to your account",
        "security.signOutOthers": "Sign out other devices",
        "security.passUpdatedToast": "Password updated successfully",

        // Notifications Page
        "notif.title": "Notifications & Alerts",
        "notif.subtitle": "Choose how and when to receive bill reminders and balance warnings",
        "notif.push": "Desktop & Browser Push",
        "notif.pushDesc": "Receive real-time alerts even when Nomadix is running in the background",
        "notif.enablePush": "Enable Push Alerts",
        "notif.subsSection": "Subscriptions & Due Dates",
        "notif.sub1d": "1-Day Due Date Alert",
        "notif.sub3d": "3-Day Advance Warning",
        "notif.subPrice": "Price Changes & Trial Expirations",
        "notif.vaultsSection": "Vaults & Balance Alerts",
        "notif.vaultLow": "Low Balance Warnings",
        "notif.vaultLowDesc": "Notify when a vault has insufficient balance for upcoming charges",
        "notif.receivableReminder": "Pending Collection Reminders",
        "notif.receivableReminderDesc": "Notify when a receivable is due soon or overdue",
        "notif.emailSection": "Email Delivery",
        "notif.emailWeekly": "Weekly Spending Summary",

        // Billing Page
        "billing.title": "Billing & Subscription",
        "billing.subtitle": "Manage your Nomadix Pro membership, payment cycle, and invoices",
        "billing.planName": "Nomadix Premium Plan",
        "billing.active": "Active",
        "billing.monthly": "Monthly",
        "billing.annual": "Annual",
        "billing.saveBadge": "Save 25%",
        "billing.manage": "Manage Plan",
        "billing.included": "Included in your plan",
        "billing.usage": "Account Usage",
        "billing.receipts": "Payment Receipts & Invoices",

        // Language Page
        "lang.title": "Language & Regional Settings",
        "lang.subtitle": "Customize interface language, numeric decimal formats, and date displays",
        "lang.preview": "Live Regional Formatting Preview",
        "lang.datePreview": "Current Date",
        "lang.numberPreview": "Expense Sample",
        "lang.firstDayPreview": "First Day of Week",
        "lang.displayLang": "Display Language",
        "lang.formatsSection": "Date & Number Formats",
        "lang.dateFormat": "Date Format",
        "lang.numberFormat": "Number & Decimal Separator",
        "lang.firstDay": "First Day of Week",
        "lang.monday": "Monday",
        "lang.sunday": "Sunday",
        "lang.save": "Save Preferences",

        // Support Page
        "support.title": "Help & Support",
        "support.subtitle": "Frequently asked questions, helpdesk contact, and system status",
        "support.docs": "Documentation",
        "support.community": "Nomad Community",
        "support.status": "System Status",
        "support.faq": "Frequently Asked Questions",
        "support.contact": "Contact Nomadix Support",
        "support.category": "Category",
        "support.priority": "Priority",
        "support.subject": "Subject",
        "support.message": "Message",
        "support.send": "Submit Ticket",

        // Data Page
        "data.title": "Data Management & Privacy",
        "data.subtitle": "Export your complete transaction history, backup vaults, and control account data",
        "data.exportSection": "Export Data",
        "data.jsonTitle": "Complete JSON Backup",
        "data.jsonDesc": "Download all your vaults, subscriptions, identity document records, and transactions.",
        "data.downloadJson": "Download JSON",
        "data.csvTitle": "Transactions Spreadsheet (CSV)",
        "data.csvDesc": "Export your spending, transfers, and category metadata for accounting or tax filing.",
        "data.downloadCsv": "Download CSV",
        "data.danger": "Danger Zone",
        "data.deleteTitle": "Delete Account & Personal Data",
        "data.deleteDesc": "Permanently wipe your vaults, transactions, and documents. Cannot be reversed.",
        "data.deleteBtn": "Delete Account Data",

        // Friends
        "friends.title": "Friends",
        "friends.subtitle": "Add friends to transfer money and split expenses.",
        "friends.searchPlaceholder": "Search by @username or NMDX-XXXX code",
        "friends.searchButton": "Search",
        "friends.searchHint": "You can never search for someone by email.",
        "friends.searchNoResults": "No user found matching that.",
        "friends.sendRequest": "Add",
        "friends.requestSent": "Request sent",
        "friends.tabFriends": "Friends",
        "friends.tabRequests": "Requests",
        "friends.tabBalances": "Balances",
        "friends.balancesComingSoon": "Shared-expense balances are coming in the next phase.",
        "friends.noFriendsYet": "You haven't added any friends yet",
        "friends.noFriendsYetDesc": "Search for someone by their username or friend code to get started.",
        "friends.noRequests": "No pending requests",
        "friends.incomingRequests": "Sent to you",
        "friends.outgoingRequests": "Sent by you",
        "friends.accept": "Accept",
        "friends.decline": "Decline",
        "friends.cancelRequest": "Cancel",
        "friends.remove": "Remove friend",
        "friends.block": "Block",
        "friends.unblock": "Unblock",
        "friends.confirmRemove": "Remove this friend?",
        "friends.confirmBlock": "Block this user? They won't be able to message you again.",
        "friends.outstandingBalance": "You have an outstanding balance with this friend. Settle it first, or force the removal (the balance is written off).",
        "friends.forceRemove": "Remove anyway",
        "friends.since": "Friends since {date}",
        "friends.you": "You",
        "friends.actionFailed": "Couldn't complete that action",

        // Settings > Privacy & Friends (identity)
        "socialPrivacy.title": "Privacy & Friends",
        "socialPrivacy.subtitle": "Your public identity and who can find you.",
        "socialPrivacy.identitySection": "Your Identity",
        "socialPrivacy.usernameLabel": "Username",
        "socialPrivacy.usernamePlaceholder": "your_username",
        "socialPrivacy.usernameHint": "3-20 characters: letters, numbers, underscore. You can change it every 30 days.",
        "socialPrivacy.usernameSave": "Save username",
        "socialPrivacy.usernameCooldown": "You can change your username again in {days} days.",
        "socialPrivacy.usernameTaken": "That username is already taken.",
        "socialPrivacy.usernameSaved": "Username updated",
        "socialPrivacy.friendCodeLabel": "Your friend code",
        "socialPrivacy.friendCodeHint": "Share it so someone can add you without searching your username.",
        "socialPrivacy.friendCodeCopy": "Copy",
        "socialPrivacy.friendCodeCopied": "Code copied",
        "socialPrivacy.friendCodeRegenerate": "Generate new code",
        "socialPrivacy.friendCodeRegenerateHint": "The old code stops working immediately.",
        "socialPrivacy.friendCodeRegenerated": "New code generated",
        "socialPrivacy.discoverableLabel": "Allow people to find me",
        "socialPrivacy.discoverableDesc": "When off, nobody can find you by username or code, or send you friend requests.",
        "socialPrivacy.vaultsSection": "Transfers into my vaults",
        "socialPrivacy.vaultsComingSoon": "Per-vault privacy (who can transfer money to you) arrives in the next phase. Your balance is never visible to anyone else, under any circumstance.",
        "socialPrivacy.balanceNeverShown": "Your balance is never shown to your friends.",
        "socialPrivacy.vaultPolicyNobody": "Closed",
        "socialPrivacy.vaultPolicyNobodyDesc": "Nobody can transfer money into this vault.",
        "socialPrivacy.vaultPolicyFriends": "All my friends",
        "socialPrivacy.vaultPolicyFriendsDesc": "Any accepted friend can transfer into this vault.",
        "socialPrivacy.vaultPolicyAllowlist": "Selected friends",
        "socialPrivacy.vaultPolicyAllowlistDesc": "Only the friends you pick can transfer into this vault.",
        "socialPrivacy.selectFriends": "Choose friends",
        "socialPrivacy.noFriendsToSelect": "You don't have any friends to select yet.",
        "socialPrivacy.notePlaceholder": "Note shown to whoever transfers to you (optional)",
        "socialPrivacy.policySaved": "Vault privacy updated",
        "socialPrivacy.savePolicy": "Save",

        // Transfers
        "transfer.send": "Send",
        "transfer.sendTo": "Send to {name}",
        "transfer.fromVault": "From your vault",
        "transfer.toVault": "To {name}'s vault",
        "transfer.selectVault": "Select a vault",
        "transfer.noOpenVaults": "{name} has no vaults open to transfers from you.",
        "transfer.amount": "Amount",
        "transfer.includeFee": "Include a fee?",
        "transfer.totalDebited": "{amount} will be debited from your vault",
        "transfer.note": "Note (optional)",
        "transfer.willReceive": "{name} will receive approximately {amount}",
        "transfer.confirm": "Confirm send",
        "transfer.sent": "Transfer sent",
        "transfer.sendFailed": "Couldn't send the transfer",
        "transfer.insufficientFunds": "Insufficient funds in the source vault",
        "transfer.notAllowed": "That transfer isn't allowed",
        "transfer.recentTitle": "Recent transfers",
        "transfer.noneYet": "No transfers yet",
        "transfer.returnAction": "Return",
        "transfer.returnConfirm": "Return this transfer?",
        "transfer.returned": "Transfer returned",
        "transfer.returnFailed": "Couldn't return the transfer",
        "transfer.reversibleFor": "Can still be returned for {hours}h {minutes}m",
        "transfer.windowExpired": "No longer returnable",
        "transfer.reversedBadge": "Returned",
        "transfer.sentTo": "You sent to {name}",
        "transfer.receivedFrom": "You received from {name}",

        // Shared vaults
        "sharedVault.badge": "Shared",
        "sharedVault.shareAction": "Share vault",
        "sharedVault.leaveAction": "Leave vault",
        "sharedVault.dissolveAction": "Dissolve shared vault",
        "sharedVault.selectFriend": "Pick a friend to share this vault with",
        "sharedVault.invited": "Invite sent",
        "sharedVault.inviteFailed": "Couldn't send the invite",
        "sharedVault.pendingInvite": "{name} invited you to share \"{vault}\"",
        "sharedVault.accept": "Accept",
        "sharedVault.decline": "Decline",
        "sharedVault.accepted": "You now share this vault",
        "sharedVault.declined": "Invite declined",
        "sharedVault.leftVault": "You left the shared vault",
        "sharedVault.leaveFailed": "Couldn't leave the vault",
        "sharedVault.confirmLeave": "Leave this shared vault?",
        "sharedVault.with": "Shared with {name}",

        // Splits
        "split.action": "Split with a friend",
        "split.modalTitle": "Split expense",
        "split.selectFriend": "Friend",
        "split.modeEqual": "50 / 50",
        "split.modeAmount": "Amount",
        "split.modePercent": "Percent",
        "split.theyOwe": "{name} owes you {amount}",
        "split.youOwe": "You owe {name} {amount}",
        "split.confirm": "Create split",
        "split.created": "Expense split",
        "split.createFailed": "Couldn't split the expense",
        "split.badge": "Split",
        "split.void": "Void split",
        "split.voided": "Split voided",
        "split.reject": "Not mine",
        "split.rejected": "Split rejected",
        "split.alreadySettled": "This split was already settled",
        "split.notSharable": "This vault is already shared -- it cannot also be split with someone else.",

        // Balances (Friends > Balances tab)
        "balances.title": "Balances with friends",
        "balances.allSettled": "You're all settled up with your friends",
        "balances.owesYou": "{name} owes you",
        "balances.youOwe": "You owe {name}",
        "balances.settleUp": "Settle up",
        "balances.settleUpTitle": "Settle up with {name}",
        "balances.settleAmount": "Amount to settle",
        "balances.settleFromVault": "From your vault",
        "balances.settleToVault": "To {name}'s vault",
        "balances.settled": "Balance settled",
        "balances.settleFailed": "Couldn't settle the balance",
        "balances.nothingToSettle": "Nothing to settle with this friend",

        // Common (shared across small forms/modals)
        "common.cancel": "Cancel",
        "common.confirm": "Confirm",
        "common.edit": "Edit",
        "common.save": "Save Changes",
        "common.saving": "Saving...",
        "common.optional": "optional",

        // Receivables (Pending Collection)
        "nav.receivables": "Receivables",
        "receivables.title": "Pending Collection",
        "receivables.subtitle": "Money you've invoiced that clients haven't paid yet.",
        "receivables.mustBeLoggedIn": "You must be logged in to view your receivables.",
        "receivables.tablesNotSetUp": "This feature isn't set up yet. Contact support.",
        "receivables.new": "New Account",
        "receivables.manageClients": "Clients",
        "receivables.noResults": "No accounts match this filter.",
        "receivables.emptyVaultTitle": "You don't have a collection vault yet",
        "receivables.emptyVaultBody": "Create a \"Pending Collection\" type vault from Vaults to start tracking receivables.",
        "receivables.emptyVaultCta": "Go to Vaults",
        "receivables.stats.outstanding": "Outstanding",
        "receivables.stats.overdue": "Overdue",
        "receivables.stats.overdueHint": "Needs follow-up",
        "receivables.stats.dueThisMonth": "Due This Month",
        "receivables.stats.collectedThisMonth": "Collected This Month",
        "receivables.filter.all": "All",
        "receivables.filter.pending": "Pending",
        "receivables.filter.overdue": "Overdue",
        "receivables.filter.paid": "Collected",
        "receivables.newTitle": "New Pending Account",
        "receivables.editTitle": "Edit Pending Account",
        "receivables.newSubtitle": "Track invoiced money you're waiting to collect",
        "receivables.field.vault": "Vault",
        "receivables.field.client": "Client",
        "receivables.field.description": "Description",
        "receivables.field.amount": "Amount",
        "receivables.field.currency": "Currency",
        "receivables.field.issueDate": "Issue Date",
        "receivables.field.expectedDate": "Expected Payment Date",
        "receivables.field.reminder": "Collection Reminder",
        "receivables.field.reminderHint": "Notify before the expected date",
        "receivables.field.reminderDaysSuffix": "days before",
        "receivables.field.notes": "Notes",
        "receivables.toast.created": "Pending account created",
        "receivables.toast.updated": "Pending account updated",
        "receivables.toast.collected": "Collection recorded",
        "receivables.toast.canceled": "Pending account canceled",
        "receivables.detail.outstanding": "Outstanding",
        "receivables.detail.collected": "Collected",
        "receivables.detail.collectedOfTotal": "collected of",
        "receivables.detail.overdueWarning": "This account is overdue.",
        "receivables.detail.collectAction": "Record Collection",
        "receivables.detail.cancelAction": "Cancel Account",
        "receivables.collect.title": "Record Collection",
        "receivables.collect.outstanding": "Outstanding",
        "receivables.collect.destinationVault": "Destination Vault",
        "receivables.collect.amountToCollect": "Amount to Collect",
        "receivables.collect.partialHint": "This will be recorded as a partial collection.",
        "receivables.collect.exchangeRate": "Exchange Rate",
        "receivables.collect.rateHint": "Different currencies -- enter the conversion rate.",
        "receivables.collect.noLiquidVaults": "You need at least one liquid vault (Savings, Checking or Cash) to receive the collection.",
        "receivables.collect.selectVault": "Select a destination vault.",
        "receivables.collect.invalidAmount": "Enter a valid amount.",
        "receivables.collect.exceedsOutstanding": "Amount exceeds the outstanding balance.",
        "receivables.collect.invalidRate": "Enter a valid exchange rate.",
        "receivables.collect.confirm": "Confirm Collection",
        "receivables.clients.title": "Clients",
        "receivables.clients.subtitle": "People or companies who owe you money.",
        "receivables.clients.addPlaceholder": "Client name…",
        "receivables.clients.empty": "You don't have any clients yet.",
        "receivables.clients.archive": "Archive",
        "receivables.clients.unarchive": "Restore",
        "receivables.clients.archived": "Archived",
    },
    de: {} as any,
    fr: {} as any,
    pt: {} as any,
};

// Fallbacks for other languages to English
TRANSLATIONS.de = { ...TRANSLATIONS.en, "nav.dashboard": "Übersicht", "nav.vaults": "Tresore", "nav.expenses": "Ausgaben", "nav.settings": "Einstellungen" };
TRANSLATIONS.fr = { ...TRANSLATIONS.en, "nav.dashboard": "Tableau de bord", "nav.vaults": "Coffres", "nav.expenses": "Dépenses", "nav.settings": "Paramètres" };
TRANSLATIONS.pt = { ...TRANSLATIONS.en, "nav.dashboard": "Painel", "nav.vaults": "Cofres", "nav.expenses": "Despesas", "nav.settings": "Configurações" };

function loadSavedSettings(): RegionalSettings {
    if (typeof window === "undefined") return DEFAULT_SETTINGS;
    try {
        const raw = localStorage.getItem(STORAGE_KEY);
        const legacyLang = localStorage.getItem(LANG_STORAGE_KEY) as LanguageCode | null;
        if (raw) {
            const parsed = JSON.parse(raw);
            return {
                ...DEFAULT_SETTINGS,
                ...parsed,
                language: legacyLang || parsed.language || DEFAULT_SETTINGS.language,
            };
        }
        if (legacyLang) {
            return { ...DEFAULT_SETTINGS, language: legacyLang };
        }
        return DEFAULT_SETTINGS;
    } catch {
        return DEFAULT_SETTINGS;
    }
}

interface LanguageState extends RegionalSettings {
    setLanguage: (lang: LanguageCode) => void;
    setRegionalPrefs: (prefs: Partial<RegionalSettings>) => void;
    t: (key: string, vars?: Record<string, string | number>) => string;
    formatDate: (date: Date | string | number) => string;
    formatNumber: (amount: number, symbol?: string) => string;
}

export const useLanguageStore = create<LanguageState>((set, get) => ({
    ...loadSavedSettings(),

    setLanguage: (lang: LanguageCode) => {
        set({ language: lang });
        if (typeof window !== "undefined") {
            localStorage.setItem(LANG_STORAGE_KEY, lang);
            const current = loadSavedSettings();
            localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...current, language: lang }));
        }
    },

    setRegionalPrefs: (prefs: Partial<RegionalSettings>) => {
        set((state) => {
            const next = { ...state, ...prefs };
            if (typeof window !== "undefined") {
                localStorage.setItem(
                    STORAGE_KEY,
                    JSON.stringify({
                        language: next.language,
                        dateFormat: next.dateFormat,
                        numberFormat: next.numberFormat,
                        firstDayOfWeek: next.firstDayOfWeek,
                    })
                );
                if (prefs.language) {
                    localStorage.setItem(LANG_STORAGE_KEY, prefs.language);
                }
            }
            return next;
        });
    },

    t: (key: string, vars?: Record<string, string | number>): string => {
        const lang = get().language;
        const dict = TRANSLATIONS[lang] || TRANSLATIONS.es;
        const template = dict[key] || TRANSLATIONS.en[key] || key;
        if (!vars) return template;
        return template.replace(/\{(\w+)\}/g, (match, name) =>
            name in vars ? String(vars[name]) : match
        );
    },

    formatDate: (dateInput: Date | string | number): string => {
        const d = new Date(dateInput);
        if (isNaN(d.getTime())) return "";
        const { dateFormat } = get();
        const dd = String(d.getDate()).padStart(2, "0");
        const mm = String(d.getMonth() + 1).padStart(2, "0");
        const yyyy = d.getFullYear();

        if (dateFormat === "MM/DD/YYYY") return `${mm}/${dd}/${yyyy}`;
        if (dateFormat === "YYYY-MM-DD") return `${yyyy}-${mm}-${dd}`;
        return `${dd}/${mm}/${yyyy}`;
    },

    formatNumber: (amount: number, symbol = ""): string => {
        const { numberFormat } = get();
        if (numberFormat === "de") {
            return `${amount.toLocaleString("de-DE", {
                minimumFractionDigits: 2,
                maximumFractionDigits: 2,
            })} ${symbol}`.trim();
        }
        return `${symbol}${amount.toLocaleString("en-US", {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
        })}`.trim();
    },
}));
